/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Conexion;
import java.awt.Color;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class Citas extends javax.swing.JPanel {

      DefaultTableModel modeloCitas = new DefaultTableModel();
     // String sql="SELECT * FROM producto";
     Conexion con = new Conexion();
      Connection cn= con.ConectarBaseDatos();
    /**
     * Creates new form Productos
     */
    public Citas() {
        initComponents();
        recuperarPacientes();
        recuperarEmpleados();
        jTableCitas.setValueAt("8:00", 0, 0);
        jTableCitas.setValueAt("8:30", 1, 0);
        jTableCitas.setValueAt("9:00", 2, 0);
        jTableCitas.setValueAt("9:30", 3, 0);
        jTableCitas.setValueAt("10:00", 4, 0);
        jTableCitas.setValueAt("10:30", 5, 0);
        jTableCitas.setValueAt("11:00", 6, 0);
        jTableCitas.setValueAt("11:30", 7, 0);
        jTableCitas.setValueAt("12:00", 8, 0);
        jTableCitas.setValueAt("12:30", 9, 0);
        jTableCitas.setValueAt("13:00", 10, 0);
        jTableCitas.setValueAt("13:30", 11, 0);
        jTableCitas.setValueAt("14:00", 12, 0);
        jTableCitas.setValueAt("14:30", 13, 0);
        jTableCitas.setValueAt("15:00", 14, 0);
        jTableCitas.setValueAt("15:30", 15, 0);
        jTableCitas.setValueAt("16:00", 16, 0);
        jTableCitas.setValueAt("16:30", 17, 0);
        jTableCitas.setValueAt("17:00", 18, 0);
        jTableCitas.setValueAt("17:30", 19, 0);
        jTableCitas.setValueAt("18:00", 20, 0);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxEncargado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxPacientes = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCitas = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(36, 41, 46));
        setPreferredSize(new java.awt.Dimension(1420, 810));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(51, 153, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Encargado:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 100, 110, 21);

        jPanel1.add(jComboBoxEncargado);
        jComboBoxEncargado.setBounds(190, 94, 280, 30);

        jLabel6.setBackground(new java.awt.Color(51, 153, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("CONTROL DE CITAS");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(560, 30, 210, 26);

        jLabel7.setBackground(new java.awt.Color(51, 153, 255));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Hora fin:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 340, 110, 21);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/2 hora", "1 Hora", "1 1/2 hora y media ", "2 horas", " " }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(190, 214, 280, 30);

        jLabel8.setBackground(new java.awt.Color(51, 153, 255));
        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Paciente:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 140, 110, 21);

        jLabel9.setBackground(new java.awt.Color(51, 153, 255));
        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Fecha:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 180, 110, 21);

        jPanel1.add(jComboBoxPacientes);
        jComboBoxPacientes.setBounds(190, 140, 280, 30);

        jLabel10.setBackground(new java.awt.Color(51, 153, 255));
        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Hora inicio:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 300, 110, 21);

        jTableCitas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTableCitas.setForeground(new java.awt.Color(0, 0, 0));
        jTableCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hora", "SILLA 1 ", "SILLA 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCitas.setRowHeight(50);
        jTableCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCitasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableCitasMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCitas);
        if (jTableCitas.getColumnModel().getColumnCount() > 0) {
            jTableCitas.getColumnModel().getColumn(0).setResizable(false);
            jTableCitas.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableCitas.getColumnModel().getColumn(1).setResizable(false);
            jTableCitas.getColumnModel().getColumn(1).setPreferredWidth(350);
            jTableCitas.getColumnModel().getColumn(2).setResizable(false);
            jTableCitas.getColumnModel().getColumn(2).setPreferredWidth(350);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(50, 370, 1290, 420);

        jLabel11.setBackground(new java.awt.Color(51, 153, 255));
        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Duración:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 220, 110, 21);

        jLabel12.setBackground(new java.awt.Color(51, 153, 255));
        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Silla:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 260, 110, 21);

        jLabel13.setBackground(new java.awt.Color(51, 153, 255));
        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("-------");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(190, 300, 110, 21);

        jLabel14.setBackground(new java.awt.Color(51, 153, 255));
        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("-------");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(190, 340, 110, 21);

        jLabel15.setBackground(new java.awt.Color(51, 153, 255));
        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("-------");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(190, 260, 110, 21);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCitasMouseClicked
      
    }//GEN-LAST:event_jTableCitasMouseClicked

    private void jTableCitasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCitasMouseReleased
   jTableCitas.setSelectionBackground(Color.yellow);
     boolean x = jTableCitas.getCellSelectionEnabled();
      int registro = jTableCitas.getSelectedRow();
        int columna = jTableCitas.getSelectedColumn();  
        System.out.println("fila : " + registro);
        System.out.println("columna : " + columna);
        
           
    }//GEN-LAST:event_jTableCitasMouseReleased

   
    
    
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxEncargado;
    private javax.swing.JComboBox<String> jComboBoxPacientes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCitas;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    public void recuperarPacientes(){
        Conexion con = new Conexion();
        Connection cn = con.ConectarBaseDatos();
        String sql = "SELECT id, Nombre FROM Paciente";
        String[] datos = new String[5];
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                jComboBoxPacientes.addItem(String.valueOf(rs.getInt(1)) +"  -  "+ rs.getString(2));                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void recuperarEmpleados(){
        Conexion con = new Conexion();
        Connection cn = con.ConectarBaseDatos();
        String sql = "SELECT id, Nombres,Apellidos FROM RecursosHumanos WHERE Acceso = TRUE";
        String[] datos = new String[5];
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                jComboBoxEncargado.addItem(String.valueOf(rs.getInt(1)) +"  -  "+ rs.getString(2) + "  " + rs.getString(3));                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
