/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author igeni
 */
public class IngresoEmpleados extends javax.swing.JPanel {

    Clases.Conexion conexion = new Clases.Conexion();
    Clases.InsertarEmpleado Insercion = new Clases.InsertarEmpleado();
    Clases.Contrasena encriptado = new Clases.Contrasena();
    Clases.Telefono telefono = new Clases.Telefono();
    DefaultTableModel empleados = new DefaultTableModel();
    DefaultTableModel clientes = new DefaultTableModel();
    int seleccionado = 0;
    int seltel = 0;
    int idseleccionado = 0;
    
    public IngresoEmpleados() {
        initComponents();
        BTNEliEmpleado.setEnabled(false);
        conexion.ConectarBaseDatos();
        TFNombres.setEnabled(true);
        TFDireccion.setEnabled(true);
        TFApellidos.setEnabled(true);
        TFMNombre.setEnabled(false);
        TFMApellidos.setEnabled(false);
        TFMDireccion.setEnabled(false);
        TFTelefono1.setEnabled(false);
        BTNAgregar.setEnabled(true);
        TFUsuario.setEnabled(true);
        PFContrasena.setEnabled(true);
        BTNTelefono.setEnabled(false);
        TFTelefono.setEnabled(false);
        BTNModEmpleado.setEnabled(false);
        BTNModCel.setEnabled(false);
        BTNEliEmpleado.setEnabled(false);
        BTNEliTel.setEnabled(false);
        RBVendedor.setEnabled(true);
        RBAdministrador.setEnabled(true);
        empleados.addColumn("Código");
        empleados.addColumn("Nombres");
        empleados.addColumn("Apellidos");
        empleados.addColumn("Dirección");
        empleados.addColumn("Estado");
        empleados.addColumn("Usuario");
        empleados.addColumn("Rol");
        TEmpleados.setModel(empleados);
        clientes.addColumn("Telefonos");
        TTelefonos.setModel(clientes);
        Insercion.Buscar(empleados);
        //Insercion.Buscar(jComboBox1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        LBLPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PTelefono = new javax.swing.JPanel();
        BTNEliTel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TTelefonos = new javax.swing.JTable();
        BTNModCel = new javax.swing.JButton();
        PIngresoTelefono = new javax.swing.JPanel();
        LBLTelefono = new javax.swing.JLabel();
        BTNTelefono = new javax.swing.JButton();
        TFTelefono = new javax.swing.JTextField();
        LBLMTelefono = new javax.swing.JLabel();
        LBLBusqTel = new javax.swing.JLabel();
        TFFiltro1 = new javax.swing.JTextField();
        TFTelefono1 = new javax.swing.JTextField();
        PEmpleados = new javax.swing.JPanel();
        BTNEliEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEmpleados = new javax.swing.JTable();
        LBLMApellidos = new javax.swing.JLabel();
        LBLMDireccion = new javax.swing.JLabel();
        BTNModEmpleado = new javax.swing.JButton();
        LBLMNombre = new javax.swing.JLabel();
        PIngresoEmpleado = new javax.swing.JPanel();
        LBLApellidos = new javax.swing.JLabel();
        LBLDireccion = new javax.swing.JLabel();
        LBLNombre = new javax.swing.JLabel();
        RBVendedor = new javax.swing.JRadioButton();
        RBAdministrador = new javax.swing.JRadioButton();
        TFNombres = new javax.swing.JTextField();
        TFApellidos = new javax.swing.JTextField();
        TFDireccion = new javax.swing.JTextField();
        PAdministrador = new javax.swing.JPanel();
        LBLUsuario = new javax.swing.JLabel();
        LBLContrasena = new javax.swing.JLabel();
        PFContrasena = new javax.swing.JPasswordField();
        BTNAgregar = new javax.swing.JButton();
        TFUsuario = new javax.swing.JTextField();
        RBMejorAmigo = new javax.swing.JRadioButton();
        RBMascota = new javax.swing.JRadioButton();
        TFRespuesta = new javax.swing.JTextField();
        LBLUsuario1 = new javax.swing.JLabel();
        RBDeporte = new javax.swing.JRadioButton();
        LBLUsuario2 = new javax.swing.JLabel();
        LBLIngresoEmpleado = new javax.swing.JLabel();
        LBLBusqEmpleado = new javax.swing.JLabel();
        TFMNombre = new javax.swing.JTextField();
        TFMApellidos = new javax.swing.JTextField();
        TFMDireccion = new javax.swing.JTextField();
        TFFiltro = new javax.swing.JTextField();

        panel1.setBackground(new java.awt.Color(36, 41, 46));

        LBLPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLPanel.setForeground(new java.awt.Color(255, 255, 255));
        LBLPanel.setText("Ingreso de empleados");

        jPanel2.setBackground(new java.awt.Color(36, 41, 46));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1871, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        PTelefono.setBackground(new java.awt.Color(0, 51, 102));

        BTNEliTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminarp.png"))); // NOI18N
        BTNEliTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliTelActionPerformed(evt);
            }
        });

        TTelefonos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TTelefonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teléfono"
            }
        ));
        TTelefonos.setFocusable(false);
        TTelefonos.getTableHeader().setReorderingAllowed(false);
        TTelefonos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TTelefonosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TTelefonos);

        BTNModCel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificarp.png"))); // NOI18N
        BTNModCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModCelActionPerformed(evt);
            }
        });

        PIngresoTelefono.setBackground(new java.awt.Color(36, 41, 46));

        LBLTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLTelefono.setForeground(new java.awt.Color(255, 255, 255));
        LBLTelefono.setText("Teléfono/Celular del empleado:");

        BTNTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_telefono.png"))); // NOI18N
        BTNTelefono.setBorder(null);
        BTNTelefono.setBorderPainted(false);
        BTNTelefono.setContentAreaFilled(false);
        BTNTelefono.setFocusPainted(false);
        BTNTelefono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNTelefono.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_telefono2.png"))); // NOI18N
        BTNTelefono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_telefono1.png"))); // NOI18N
        BTNTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTelefonoActionPerformed(evt);
            }
        });

        TFTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFTelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PIngresoTelefonoLayout = new javax.swing.GroupLayout(PIngresoTelefono);
        PIngresoTelefono.setLayout(PIngresoTelefonoLayout);
        PIngresoTelefonoLayout.setHorizontalGroup(
            PIngresoTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIngresoTelefonoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PIngresoTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        PIngresoTelefonoLayout.setVerticalGroup(
            PIngresoTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIngresoTelefonoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LBLTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BTNTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        LBLMTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLMTelefono.setForeground(new java.awt.Color(255, 255, 255));
        LBLMTelefono.setText("Teléfono/Celular del empleado:");

        LBLBusqTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqTel.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqTel.setText("Buscar por nombre:");

        TFFiltro1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFFiltro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFFiltro1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFiltro1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFFiltro1KeyTyped(evt);
            }
        });

        TFTelefono1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFTelefono1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PTelefonoLayout = new javax.swing.GroupLayout(PTelefono);
        PTelefono.setLayout(PTelefonoLayout);
        PTelefonoLayout.setHorizontalGroup(
            PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTelefonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLBusqTel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PTelefonoLayout.createSequentialGroup()
                        .addGroup(PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTelefonoLayout.createSequentialGroup()
                                    .addComponent(LBLMTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(131, 131, 131))
                                .addComponent(TFTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PTelefonoLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNModCel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNEliTel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TFFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156)
                .addComponent(PIngresoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PTelefonoLayout.setVerticalGroup(
            PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTelefonoLayout.createSequentialGroup()
                .addGroup(PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTelefonoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLBusqTel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNModCel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNEliTel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBLMTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PTelefonoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(PIngresoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        PEmpleados.setBackground(new java.awt.Color(0, 51, 102));

        BTNEliEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminarp.png"))); // NOI18N
        BTNEliEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliEmpleadoActionPerformed(evt);
            }
        });

        TEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Dirección", "Usuario"
            }
        ));
        TEmpleados.setFocusable(false);
        TEmpleados.getTableHeader().setReorderingAllowed(false);
        TEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TEmpleados);

        LBLMApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLMApellidos.setForeground(new java.awt.Color(255, 255, 255));
        LBLMApellidos.setText("Apellidos:");

        LBLMDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLMDireccion.setForeground(new java.awt.Color(255, 255, 255));
        LBLMDireccion.setText("Dirección:");

        BTNModEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificarp.png"))); // NOI18N
        BTNModEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModEmpleadoActionPerformed(evt);
            }
        });

        LBLMNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLMNombre.setForeground(new java.awt.Color(255, 255, 255));
        LBLMNombre.setText("Nombres:");

        PIngresoEmpleado.setBackground(new java.awt.Color(36, 41, 46));

        LBLApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLApellidos.setForeground(new java.awt.Color(255, 255, 255));
        LBLApellidos.setText("Apellidos:");

        LBLDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLDireccion.setForeground(new java.awt.Color(255, 255, 255));
        LBLDireccion.setText("Dirección:");

        LBLNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLNombre.setForeground(new java.awt.Color(255, 255, 255));
        LBLNombre.setText("Nombres:");

        RBVendedor.setBackground(new java.awt.Color(36, 41, 46));
        RBVendedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBVendedor.setForeground(new java.awt.Color(255, 255, 255));
        RBVendedor.setText("Vendedor");
        RBVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBVendedorActionPerformed(evt);
            }
        });

        RBAdministrador.setBackground(new java.awt.Color(36, 41, 46));
        RBAdministrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        RBAdministrador.setText("Administrador");
        RBAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBAdministradorActionPerformed(evt);
            }
        });

        TFNombres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFNombresKeyTyped(evt);
            }
        });

        TFApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFApellidosKeyTyped(evt);
            }
        });

        TFDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFDireccionKeyTyped(evt);
            }
        });

        PAdministrador.setBackground(new java.awt.Color(36, 41, 46));

        LBLUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsuario.setText("Usuario:");

        LBLContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLContrasena.setForeground(new java.awt.Color(255, 255, 255));
        LBLContrasena.setText("Contraseña:");

        PFContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PFContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PFContrasenaKeyTyped(evt);
            }
        });

        BTNAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado.png"))); // NOI18N
        BTNAgregar.setBorder(null);
        BTNAgregar.setBorderPainted(false);
        BTNAgregar.setContentAreaFilled(false);
        BTNAgregar.setFocusPainted(false);
        BTNAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado2.png"))); // NOI18N
        BTNAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado1.png"))); // NOI18N
        BTNAgregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAgregarActionPerformed(evt);
            }
        });

        TFUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFUsuarioKeyTyped(evt);
            }
        });

        RBMejorAmigo.setBackground(new java.awt.Color(36, 41, 46));
        RBMejorAmigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBMejorAmigo.setForeground(new java.awt.Color(255, 255, 255));
        RBMejorAmigo.setText("Conocí a mi mejor amigo en la ciudad de:");
        RBMejorAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMejorAmigoActionPerformed(evt);
            }
        });

        RBMascota.setBackground(new java.awt.Color(36, 41, 46));
        RBMascota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBMascota.setForeground(new java.awt.Color(255, 255, 255));
        RBMascota.setText("Mi mascota preferida sería:");
        RBMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMascotaActionPerformed(evt);
            }
        });

        TFRespuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFRespuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFRespuestaKeyTyped(evt);
            }
        });

        LBLUsuario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsuario1.setText("Preguntas de respaldo:");

        RBDeporte.setBackground(new java.awt.Color(36, 41, 46));
        RBDeporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBDeporte.setForeground(new java.awt.Color(255, 255, 255));
        RBDeporte.setText("Mi deporte favorito es:");
        RBDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBDeporteActionPerformed(evt);
            }
        });

        LBLUsuario2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsuario2.setText("Respuesta:");

        javax.swing.GroupLayout PAdministradorLayout = new javax.swing.GroupLayout(PAdministrador);
        PAdministrador.setLayout(PAdministradorLayout);
        PAdministradorLayout.setHorizontalGroup(
            PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAdministradorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LBLUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(TFUsuario)
                    .addComponent(BTNAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LBLContrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(PFContrasena, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addGroup(PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBDeporte)
                    .addComponent(RBMascota)
                    .addComponent(RBMejorAmigo)
                    .addComponent(LBLUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        PAdministradorLayout.setVerticalGroup(
            PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAdministradorLayout.createSequentialGroup()
                        .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBLContrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PFContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(PAdministradorLayout.createSequentialGroup()
                        .addComponent(LBLUsuario1)
                        .addGap(18, 18, 18)
                        .addComponent(RBMascota)
                        .addGap(18, 18, 18)
                        .addComponent(RBDeporte)
                        .addGap(18, 18, 18)
                        .addComponent(RBMejorAmigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBLUsuario2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout PIngresoEmpleadoLayout = new javax.swing.GroupLayout(PIngresoEmpleado);
        PIngresoEmpleado.setLayout(PIngresoEmpleadoLayout);
        PIngresoEmpleadoLayout.setHorizontalGroup(
            PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBVendedor)
                            .addComponent(RBAdministrador)))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(PAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        PIngresoEmpleadoLayout.setVerticalGroup(
            PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PAdministrador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(LBLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLApellidos)
                .addGap(4, 4, 4)
                .addComponent(TFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(RBVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBAdministrador)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        LBLIngresoEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLIngresoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        LBLIngresoEmpleado.setText("Ingresar empleado:");

        LBLBusqEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqEmpleado.setText("Buscar por nombre:");

        TFMNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFMNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFMNombreKeyTyped(evt);
            }
        });

        TFMApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFMApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFMApellidosKeyTyped(evt);
            }
        });

        TFMDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFMDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFMDireccionKeyTyped(evt);
            }
        });

        TFFiltro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFFiltroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PEmpleadosLayout = new javax.swing.GroupLayout(PEmpleados);
        PEmpleados.setLayout(PEmpleadosLayout);
        PEmpleadosLayout.setHorizontalGroup(
            PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLBusqEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addComponent(BTNEliEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTNModEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PEmpleadosLayout.createSequentialGroup()
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBLMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFMNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLIngresoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(PIngresoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2268, Short.MAX_VALUE))
        );
        PEmpleadosLayout.setVerticalGroup(
            PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadosLayout.createSequentialGroup()
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(LBLIngresoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PIngresoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBLBusqEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNEliEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BTNModEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(LBLPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(437, 437, 437)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(LBLPanel)
                .addGap(17, 17, 17)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(PEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTNEliTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliTelActionPerformed
        if (TTelefonos.getSelectedRow() != -1)
        {
            try {
                telefono.Eliminar(String.valueOf(TTelefonos.getValueAt(TTelefonos.getSelectedRow(), 0)));
                while(clientes.getRowCount()>0)
                clientes.removeRow(0);
                TFTelefono.setText("");
                TFTelefono1.setText("");
                TFFiltro1.setText("");
                TFTelefono1.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Número eliminado con éxito");
                telefono.Buscar(clientes, idseleccionado);
            } catch (SQLException ex) {
                Logger.getLogger(IngresoEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Por favor seleccione un número de teléfono");
    }//GEN-LAST:event_BTNEliTelActionPerformed

    private void TTelefonosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TTelefonosMouseClicked
        int indice = TTelefonos.getSelectedRow() + 1;
        seltel = indice;
        TableModel modelo = TTelefonos.getModel();
        BTNTelefono.setEnabled(true);
        TFTelefono.setEnabled(true);
        if (indice > 0)
        {
            LBLMTelefono.setEnabled(true);
            TFTelefono1.setEnabled(true);
            BTNModCel.setEnabled(true);
            BTNEliTel.setEnabled(true);
        }
    }//GEN-LAST:event_TTelefonosMouseClicked

    private void BTNModCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModCelActionPerformed
        if (!TFTelefono1.getText().equals(""))
        {
            if (TTelefonos.getSelectedRow() != -1)
            {

                    if(TTelefonos.getSelectedRow() != -1)
                    {
                        try {
                            telefono.Modificar(TFTelefono1.getText(), String.valueOf(TTelefonos.getValueAt(TTelefonos.getSelectedRow(), 0)));
                            while(clientes.getRowCount()>0)
                            clientes.removeRow(0);
                            telefono.Buscar(clientes, idseleccionado);
                            TFTelefono.setText("");
                            TFTelefono1.setText("");
                            TFFiltro1.setText("");
                            JOptionPane.showMessageDialog(null, "Modificación de celular exitosa");
                        } catch (SQLException ex) {
                            Logger.getLogger(IngresoEmpleados.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else
                    JOptionPane.showMessageDialog(null, "Seleccione una número de teléfono");
            }
            else
            JOptionPane.showMessageDialog(null, "Por favor seleccione un número de teléfono");
        }
        else
        JOptionPane.showMessageDialog(null, "Por favor rellene el campo de teléfono celular");
    }//GEN-LAST:event_BTNModCelActionPerformed

    private void BTNTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTelefonoActionPerformed
        while(clientes.getRowCount()>0)
        clientes.removeRow(0);
        if (TFTelefono.getText().length() > 0)
        {
            if (TEmpleados.getSelectedRow() != -1)
            {
                    try {
                        telefono.Insertar(TFTelefono.getText(), idseleccionado);
                        TFTelefono.setText("");
                        TFTelefono1.setText("");
                        TFFiltro1.setText("");
                        TFTelefono1.setEnabled(false);
                        telefono.Buscar(clientes, idseleccionado);
                    } catch (SQLException ex) {
                        Logger.getLogger(IngresoEmpleados.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Por favor seleccione un empleado)");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Por favor rellene el campo que le solicita ingresar un telefono)");
        }
    }//GEN-LAST:event_BTNTelefonoActionPerformed

    private void BTNEliEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliEmpleadoActionPerformed
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        System.out.println(TEmpleados.getSelectedRow());
        if (idseleccionado != -1)
        {
            try {
                Insercion.Eliminar(idseleccionado);
                Insercion.InsertarUsuario("", "", idseleccionado, 1);
                TFDireccion.setText("");
                TFApellidos.setText("");
                TFNombres.setText("");
                TFMNombre.setText("");
                TFMApellidos.setText("");
                TFMDireccion.setText("");
                TFUsuario.setText("");
                PFContrasena.setText("");
                TFTelefono.setText("");
                TFTelefono1.setText("");
                TFFiltro.setText("");
                TFFiltro1.setText("");
                BTNEliEmpleado.setEnabled(false);
                BTNModEmpleado.setEnabled(false);
                TFMNombre.setEnabled(false);
                TFMApellidos.setEnabled(false);
                TFMDireccion.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Empleado despedido con éxito");
            } catch (SQLException ex) {
                Logger.getLogger(IngresoEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor seleccione un empleado");
        Insercion.Buscar(empleados);
    }//GEN-LAST:event_BTNEliEmpleadoActionPerformed

    private void TEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleadosMouseClicked
        while(clientes.getRowCount()>0)
        clientes.removeRow(0);
        int indice = TEmpleados.getSelectedRow() + 1;
        seleccionado = indice;
        idseleccionado = Integer.parseInt(String.valueOf(TEmpleados.getValueAt(TEmpleados.getSelectedRow(), 0)));
        TableModel modelo = TEmpleados.getModel();
        telefono.Buscar(clientes, idseleccionado);
        BTNTelefono.setEnabled(true);
        TFTelefono.setEnabled(true);
        PIngresoTelefono.setVisible(true);
        LBLTelefono.setText("Teléfono/Celular de " + String.valueOf(empleados.getValueAt(TEmpleados.getSelectedRow(),1)));
        if (indice > 0)
        {
            BTNEliEmpleado.setEnabled(true);
            BTNModEmpleado.setEnabled(true);
            TFMNombre.setEnabled(true);
            TFMApellidos.setEnabled(true);
            TFMDireccion.setEnabled(true);
            TFUsuario.setEnabled(true);
            PFContrasena.setEnabled(true);
        }
    }//GEN-LAST:event_TEmpleadosMouseClicked

    private void BTNModEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModEmpleadoActionPerformed
        while(empleados.getRowCount()>0)
        empleados.removeRow(0);
        while(clientes.getRowCount()>0)
        clientes.removeRow(0);
        if (!TFMDireccion.getText().equals("") && !TFMNombre.getText().equals("") && !TFMApellidos.getText().equals(""))
        {
            try {
                Insercion.Modificar(TFMNombre.getText(), TFMApellidos.getText(), TFMDireccion.getText(), idseleccionado);
                JOptionPane.showMessageDialog(null, "Modificación exitosa");
                TFDireccion.setText("");
                TFApellidos.setText("");
                TFNombres.setText("");
                TFMNombre.setText("");
                TFMApellidos.setText("");
                TFMDireccion.setText("");
                TFUsuario.setText("");
                PFContrasena.setText("");
                TFTelefono.setText("");
                TFTelefono1.setText("");
                TFFiltro1.setText("");
                TFFiltro.setText("");
                BTNEliEmpleado.setEnabled(false);
                BTNModEmpleado.setEnabled(false);
                TFMNombre.setEnabled(false);
                TFMApellidos.setEnabled(false);
                TFMDireccion.setEnabled(false);
            } catch (SQLException ex) {
                Logger.getLogger(IngresoEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else
        {
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
            while(empleados.getRowCount()>0)
                empleados.removeRow(0);
            while(clientes.getRowCount()>0)
                clientes.removeRow(0);
        }
        seleccionado = -1;
        idseleccionado = -1;
        Insercion.Buscar(empleados);
        PIngresoTelefono.setVisible(false);
    }//GEN-LAST:event_BTNModEmpleadoActionPerformed

    private void BTNAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAgregarActionPerformed
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        seleccionado = -1;
        if (TFDireccion.getText().length() > 0 && TFApellidos.getText().length() > 0 && TFNombres.getText().length() > 0
                && TFUsuario.getText().length() > 0 && PFContrasena.getPassword().length > 0 && TFRespuesta.getText().length() > 0 &&
                (RBVendedor.isSelected() || RBAdministrador.isSelected()) && (RBMascota.isSelected() || RBDeporte.isSelected()
                || RBMejorAmigo.isSelected()))        
        {
            try {
                if (!Insercion.BuscarUsuario(TFUsuario.getText()))
                {
                    if (RBVendedor.isSelected())
                        if(RBMascota.isSelected())
                            Insercion.Insertar(TFNombres.getText(), TFApellidos.getText(), TFDireccion.getText(), TFUsuario.getText(), encriptado.Encriptar(String.valueOf(PFContrasena.getPassword())), 0, RBMascota.getText(), TFRespuesta.getText());
                        else if (RBDeporte.isSelected())
                            Insercion.Insertar(TFNombres.getText(), TFApellidos.getText(), TFDireccion.getText(), TFUsuario.getText(), encriptado.Encriptar(String.valueOf(PFContrasena.getPassword())), 0, RBDeporte.getText(), TFRespuesta.getText());
                        else if (RBMejorAmigo.isSelected())
                            Insercion.Insertar(TFNombres.getText(), TFApellidos.getText(), TFDireccion.getText(), TFUsuario.getText(), encriptado.Encriptar(String.valueOf(PFContrasena.getPassword())), 0, RBMejorAmigo.getText(), TFRespuesta.getText());
                    else if (RBAdministrador.isSelected())
                        if(RBMascota.isSelected())
                            Insercion.Insertar(TFNombres.getText(), TFApellidos.getText(), TFDireccion.getText(), TFUsuario.getText(), encriptado.Encriptar(String.valueOf(PFContrasena.getPassword())), 1, RBMascota.getText(), TFRespuesta.getText());
                        else if (RBDeporte.isSelected())
                            Insercion.Insertar(TFNombres.getText(), TFApellidos.getText(), TFDireccion.getText(), TFUsuario.getText(), encriptado.Encriptar(String.valueOf(PFContrasena.getPassword())), 1, RBDeporte.getText(), TFRespuesta.getText());
                        else if (RBMejorAmigo.isSelected())
                            Insercion.Insertar(TFNombres.getText(), TFApellidos.getText(), TFDireccion.getText(), TFUsuario.getText(), encriptado.Encriptar(String.valueOf(PFContrasena.getPassword())), 1, RBMejorAmigo.getText(), TFRespuesta.getText());
                }
                else
                    JOptionPane.showMessageDialog(null, "El usuario ingresado ya existe");
                TFDireccion.setText("");
                TFApellidos.setText("");
                TFNombres.setText("");
                TFMNombre.setText("");
                TFMApellidos.setText("");
                TFMDireccion.setText("");
                TFUsuario.setText("");
                PFContrasena.setText("");
                TFTelefono.setText("");
                TFTelefono1.setText("");
                TFFiltro.setText("");
                TFFiltro1.setText("");
                BTNEliEmpleado.setEnabled(false);                
                BTNModEmpleado.setEnabled(false);
                TFMNombre.setEnabled(false);
                TFMApellidos.setEnabled(false);
                TFMDireccion.setEnabled(false);
                RBVendedor.setSelected(false);
                RBAdministrador.setSelected(false);
                RBMascota.setSelected(false);
                RBDeporte.setSelected(false);
                RBMejorAmigo.setSelected(false);
                TFRespuesta.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(IngresoEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
            while(empleados.getRowCount()>0)
            empleados.removeRow(0);
            while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        }

        Insercion.Buscar(empleados);
    }//GEN-LAST:event_BTNAgregarActionPerformed

    private void RBVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBVendedorActionPerformed
        if (RBVendedor.isSelected())
            RBAdministrador.setSelected(false);
    }//GEN-LAST:event_RBVendedorActionPerformed

    private void RBAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBAdministradorActionPerformed
        if (RBAdministrador.isSelected())
            RBVendedor.setSelected(false);
    }//GEN-LAST:event_RBAdministradorActionPerformed

    private void TFFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltroKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z') evt.consume();
        if (TFFiltro.getText().length() > 30) evt.consume();
        
    }//GEN-LAST:event_TFFiltroKeyTyped

    private void TFMNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMNombreKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z') evt.consume();
        if (TFMNombre.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFMNombreKeyTyped

    private void TFMApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMApellidosKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z') evt.consume();
        if (TFMApellidos.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFMApellidosKeyTyped

    private void TFMDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMDireccionKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z') evt.consume();
        if (TFMDireccion.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFMDireccionKeyTyped

    private void TFNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNombresKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z') evt.consume();
        if (TFNombres.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFNombresKeyTyped

    private void TFApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFApellidosKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z') evt.consume();
        if (TFApellidos.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFApellidosKeyTyped

    private void TFDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDireccionKeyTyped
        char c = evt.getKeyChar();
        if (TFApellidos.getText().length() > 45) evt.consume();
    }//GEN-LAST:event_TFDireccionKeyTyped

    private void TFUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUsuarioKeyTyped
        char c = evt.getKeyChar();
        
    }//GEN-LAST:event_TFUsuarioKeyTyped

    private void TFFiltro1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro1KeyTyped
        char c = evt.getKeyChar();
        
        if (c < '0' || c > '9') evt.consume();
        if (TFFiltro.getText().length() > 10) evt.consume();
    }//GEN-LAST:event_TFFiltro1KeyTyped

    private void TFTelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefono1KeyTyped
        char c = evt.getKeyChar();
        
        if (c < '0' || c > '9') evt.consume();
        if (TFTelefono1.getText().length() > 10) evt.consume();
    }//GEN-LAST:event_TFTelefono1KeyTyped

    private void TFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefonoKeyTyped
        char c = evt.getKeyChar();
        
        if (c < '0' || c > '9') evt.consume();
        if (TFTelefono.getText().length() > 10) evt.consume();
    }//GEN-LAST:event_TFTelefonoKeyTyped

    private void PFContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PFContrasenaKeyTyped
        if (PFContrasena.getPassword().length > 40) evt.consume();
    }//GEN-LAST:event_PFContrasenaKeyTyped

    private void TFFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltroKeyPressed

    }//GEN-LAST:event_TFFiltroKeyPressed

    private void TFFiltro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro1KeyPressed

    }//GEN-LAST:event_TFFiltro1KeyPressed

    private void TFFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltroKeyReleased
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        if (!TFFiltro.getText().equals(""))
            Insercion.Filtro(empleados, TFFiltro.getText());
        else
            Insercion.Buscar(empleados);
    }//GEN-LAST:event_TFFiltroKeyReleased

    private void TFFiltro1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro1KeyReleased
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        if (!TFFiltro1.getText().equals(""))
            telefono.Filtro(clientes, TFFiltro1.getText(), idseleccionado);
        else
            telefono.Buscar(clientes, idseleccionado);
    }//GEN-LAST:event_TFFiltro1KeyReleased

    private void RBMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMascotaActionPerformed
        if (RBMascota.isSelected())
        {
            RBDeporte.setSelected(false);
            RBMejorAmigo.setSelected(false);
        }
    }//GEN-LAST:event_RBMascotaActionPerformed

    private void RBDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBDeporteActionPerformed
        if (RBDeporte.isSelected())
        {
            RBMascota.setSelected(false);
            RBMejorAmigo.setSelected(false);
        }
    }//GEN-LAST:event_RBDeporteActionPerformed

    private void RBMejorAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMejorAmigoActionPerformed
        if (RBMejorAmigo.isSelected())
        {
            RBMascota.setSelected(false);
            RBDeporte.setSelected(false);
        }
    }//GEN-LAST:event_RBMejorAmigoActionPerformed

    private void TFRespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFRespuestaKeyTyped
        if (TFRespuesta.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFRespuestaKeyTyped

    
        private void ValidarNombreYApellido(JTextField textfield, boolean direccion)
    {
        textfield.addKeyListener(new KeyAdapter()
{
   public void keyTyped(KeyEvent e)
   {
      char caracter = e.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         e.consume();  // ignorar el evento de teclado
      }
   }
});
        /*textfield.addKeyListener(new KeyAdapter());
        {
            public void keyTyped(KeyEvent e)
            {
                char caracter = e.getKeyChar();
                
                // Verificar si la tecla pulsada no es un digito ni una letra minuscula o mayuscula
                /*if((((caracter < '0') || (caracter > '9')) && ((caracter < 'a') || (caracter > 'z')) && ((caracter < 'A') || (caracter > 'Z'))) && (caracter == 'Ñ') && (caracter != '\b' ))
                /*{
                    if (direccion == true)
                    {
                        if (caracter != '-')
                            e.consume();  // ignorar el evento de teclado
                    }
                    else
                        e.consume();  // ignorar el evento de teclado
                }/*
            }
        });*/
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAgregar;
    private javax.swing.JButton BTNEliEmpleado;
    private javax.swing.JButton BTNEliTel;
    private javax.swing.JButton BTNModCel;
    private javax.swing.JButton BTNModEmpleado;
    private javax.swing.JButton BTNTelefono;
    private javax.swing.JLabel LBLApellidos;
    private javax.swing.JLabel LBLBusqEmpleado;
    private javax.swing.JLabel LBLBusqTel;
    private javax.swing.JLabel LBLContrasena;
    private javax.swing.JLabel LBLDireccion;
    private javax.swing.JLabel LBLIngresoEmpleado;
    private javax.swing.JLabel LBLMApellidos;
    private javax.swing.JLabel LBLMDireccion;
    private javax.swing.JLabel LBLMNombre;
    private javax.swing.JLabel LBLMTelefono;
    private javax.swing.JLabel LBLNombre;
    private javax.swing.JLabel LBLPanel;
    private javax.swing.JLabel LBLTelefono;
    private javax.swing.JLabel LBLUsuario;
    private javax.swing.JLabel LBLUsuario1;
    private javax.swing.JLabel LBLUsuario2;
    private javax.swing.JPanel PAdministrador;
    private javax.swing.JPanel PEmpleados;
    private javax.swing.JPasswordField PFContrasena;
    private javax.swing.JPanel PIngresoEmpleado;
    private javax.swing.JPanel PIngresoTelefono;
    private javax.swing.JPanel PTelefono;
    private javax.swing.JRadioButton RBAdministrador;
    private javax.swing.JRadioButton RBDeporte;
    private javax.swing.JRadioButton RBMascota;
    private javax.swing.JRadioButton RBMejorAmigo;
    private javax.swing.JRadioButton RBVendedor;
    private javax.swing.JTable TEmpleados;
    private javax.swing.JTextField TFApellidos;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFFiltro;
    private javax.swing.JTextField TFFiltro1;
    private javax.swing.JTextField TFMApellidos;
    private javax.swing.JTextField TFMDireccion;
    private javax.swing.JTextField TFMNombre;
    private javax.swing.JTextField TFNombres;
    private javax.swing.JTextField TFRespuesta;
    private javax.swing.JTextField TFTelefono;
    private javax.swing.JTextField TFTelefono1;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JTable TTelefonos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
