/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import Clases.Conexion;
import Clases.Inventarios;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ismar
 */
public final class Inventar extends javax.swing.JPanel {

        public DefaultTableModel modelo = new DefaultTableModel();
 public void mostrar_Proveedores(){
        Conexion con = new Conexion();
        Connection cn = con.ConectarBaseDatos();
        String sql = "SELECT id_Inventario,Nombre,Precio, Existencia, total FROM inventario ";
        
        modelo.addColumn("No. Registro");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Existencia");
        modelo.addColumn("Total");
        
        jTable1.setModel(modelo);
        
        String[] datos = new String[5];
        Statement st;
        
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {                
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                modelo.addRow(datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    int cont = 1;
    int modifier = 0;
    int filaSeleccionada = 0;
  

    /**
     * Creates new form proveedores
     */
    public Inventar() {
        initComponents();
        mostrar_Proveedores();
                 int gapWidth = 10;
        int gapHeight = 4;
        jTable1.setIntercellSpacing(new Dimension(gapWidth, gapHeight));
        jPanel2.setVisible(false);
        //cont = jTable1.getRowCount()+1;
        
        //cont = jTable1.getRowCount()+1;
        if(this.jTable1.getRowCount()!=0 && this.jTable1.getSelectedRow()!=-1){
cont = Integer.parseInt(jTable1.getValueAt(jTable1.getRowCount()-1, 0).toString());
}
        
        jPanel2.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indiceConsulta = new javax.swing.JTabbedPane();
        pnlVentas = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtExistencia = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtPrecio = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        btnAgregarP = new javax.swing.JButton();
        btnModificarp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlConsultas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(null);

        indiceConsulta.setForeground(new java.awt.Color(255, 255, 255));
        indiceConsulta.setToolTipText("");
        indiceConsulta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        indiceConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                indiceConsultaclick(evt);
            }
        });

        pnlVentas.setBackground(new java.awt.Color(36, 41, 46));
        pnlVentas.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(1420, 780));
        jPanel4.setMinimumSize(new java.awt.Dimension(1420, 780));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1420, 10));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 10, 740));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminarp.png"))); // NOI18N
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar_click.png"))); // NOI18N
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar_mouse.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 100, 100));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(493, 619));
        jPanel2.setMinimumSize(new java.awt.Dimension(493, 619));
        jPanel2.setPreferredSize(new java.awt.Dimension(493, 619));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cont1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 360, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PROVEEDOR");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Existencia:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Imagen:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar3.png"))); // NOI18N
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agre2.png"))); // NOI18N
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agre1.png"))); // NOI18N
        btnAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 160, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 160, 10));

        txtExistencia.setBackground(new java.awt.Color(36, 41, 46));
        txtExistencia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtExistencia.setForeground(new java.awt.Color(255, 255, 255));
        txtExistencia.setBorder(null);
        txtExistencia.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 160, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 160, 10));

        txtPrecio.setBackground(new java.awt.Color(36, 41, 46));
        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setBorder(null);
        txtPrecio.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 160, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 160, 10));

        txtNombre.setBackground(new java.awt.Color(36, 41, 46));
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 160, 30));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 500, 660));

        btnAgregarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregarp.png"))); // NOI18N
        btnAgregarP.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_click.png"))); // NOI18N
        btnAgregarP.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_mouse.png"))); // NOI18N
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });
        jPanel5.add(btnAgregarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 110));

        btnModificarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificarp.png"))); // NOI18N
        btnModificarp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificar_click.png"))); // NOI18N
        btnModificarp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificar_mouse.png"))); // NOI18N
        btnModificarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarpActionPerformed(evt);
            }
        });
        jPanel5.add(btnModificarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 100, 100));

        jTable1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No. Resgistro", "Nombre", "Nombre Empresa", "Correo Electrónico", "Dirección", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 1090, 620));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlVentas.add(jPanel4);
        jPanel4.setBounds(0, 0, 1430, 814);

        indiceConsulta.addTab("Inventario", pnlVentas);

        pnlConsultas.setBackground(new java.awt.Color(36, 41, 46));
        pnlConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        indiceConsulta.addTab("Proveedores", pnlConsultas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        indiceConsulta.addTab("veremos", jPanel1);

        add(indiceConsulta);
        indiceConsulta.setBounds(0, 0, 1375, 806);
    }// </editor-fold>//GEN-END:initComponents

    private void indiceConsultaclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indiceConsultaclick

    }//GEN-LAST:event_indiceConsultaclick

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int filaselec = jTable1.getSelectedRow();
        if (filaselec>=0) {
            JOptionPane.showMessageDialog(null, "esta seguro de eliminar a este proveedor.");
            modelo.removeRow(filaselec);
            Inventarios delete = new Inventarios();
            try {
                delete.eliminar(filaselec);
                JOptionPane.showMessageDialog(null, "Proveedor eliminado de forma permanente.");
            } catch (SQLException ex) {
                Logger.getLogger(Inventar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una casilla.");
            jPanel2.setVisible(false);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Inventarios enviar = new Inventarios();
        if (modifier==0 && filaSeleccionada ==0) {
            String Dato [] = new String[5];
            Dato[0] = String.valueOf(cont+1);
            Dato[1] = txtNombre.getText();
            Dato[2] = txtPrecio.getText();
            Dato[3] = txtExistencia.getText();
            Dato[4] = String.valueOf(Double.parseDouble(txtPrecio.getText())*Integer.parseInt(txtExistencia.getText()));

            JOptionPane.showMessageDialog(null, "Proveedor ingresado exitosamente!");
            modelo.addRow(Dato);
            jPanel2.setVisible(false);
           
            enviar.insertar(txtNombre.getText(), Double.parseDouble(txtPrecio.getText()), Integer.parseInt(txtExistencia.getText()));
            txtNombre.setText("");
            txtPrecio.setText("");
            txtExistencia.setText("");
            

            cont++;
        }
        else
        {
            int filaselect = jTable1.getSelectedRow();
            try {
                enviar.update(txtNombre.getText(), Double.parseDouble(txtPrecio.getText()), Integer.parseInt(txtExistencia.getText()),Integer.parseInt(jTable1.getValueAt(filaselect, 0).toString()));
            }   catch (SQLException ex) {
                Logger.getLogger(Inventar.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Proveedor modificado exitosamente!");
            jTable1.setValueAt(txtNombre.getText(),filaselect ,1);
            jTable1.setValueAt(txtPrecio.getText(),filaselect ,2);
            jTable1.setValueAt(txtExistencia.getText(),filaselect ,3);
            jPanel2.setVisible(false);
            txtNombre.setText("");
            txtPrecio.setText("");
            txtExistencia.setText("");
        
            filaSeleccionada=0;
            modifier=0;
        }
        //  System.out.println("SE HA ENVIADO A LA DATA BASE");

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(true);
    }//GEN-LAST:event_btnAgregarPActionPerformed

    private void btnModificarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarpActionPerformed
        // TODO add your handling code here:
        modifier=1;
        filaSeleccionada=1;
        int filaSelec = jTable1.getSelectedRow();
        if (filaSelec>=0){
            jPanel2.setVisible(true);
            txtNombre.setText(jTable1.getValueAt(filaSelec, 1).toString());
            txtPrecio.setText(jTable1.getValueAt(filaSelec, 2).toString());
            txtExistencia.setText(jTable1.getValueAt(filaSelec, 3).toString());
           
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una casilla.");
        }
    }//GEN-LAST:event_btnModificarpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnModificarp;
    private javax.swing.JTabbedPane indiceConsulta;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JPanel pnlVentas;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

}
