/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import javax.swing.JOptionPane;

/**
 *
 * @author igeni
 */
public class RecuperarContrasena extends javax.swing.JFrame {

    Clases.InsertarEmpleado vendedor = new Clases.InsertarEmpleado();
    public RecuperarContrasena() {
        initComponents();
        BTNRespuesta.setEnabled(false);
        TFRespuesta.setEnabled(false);
        PRespuesta.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel22 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BTNCuuenta = new javax.swing.JButton();
        PRespuesta = new javax.swing.JPanel();
        BTNRespuesta = new javax.swing.JButton();
        LBLPregunta = new javax.swing.JLabel();
        TFRespuesta = new javax.swing.JTextField();
        LBLContrasena = new javax.swing.JLabel();
        LBLCuenta = new javax.swing.JLabel();
        TFCuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(498, 576));
        setMinimumSize(new java.awt.Dimension(498, 576));
        setUndecorated(true);

        jPanel22.setBackground(new java.awt.Color(36, 41, 46));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel22.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 360, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida2.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida3.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida1.png"))); // NOI18N
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimiza2.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar3.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar1.png"))); // NOI18N
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        BTNCuuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar1.png"))); // NOI18N
        BTNCuuenta.setBorder(null);
        BTNCuuenta.setBorderPainted(false);
        BTNCuuenta.setContentAreaFilled(false);
        BTNCuuenta.setFocusPainted(false);
        BTNCuuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNCuuenta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar3.png"))); // NOI18N
        BTNCuuenta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar2.png"))); // NOI18N
        BTNCuuenta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNCuuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCuuentaActionPerformed(evt);
            }
        });
        jPanel22.add(BTNCuuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 130, 60));

        PRespuesta.setBackground(new java.awt.Color(36, 41, 46));

        BTNRespuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar1.png"))); // NOI18N
        BTNRespuesta.setBorder(null);
        BTNRespuesta.setBorderPainted(false);
        BTNRespuesta.setContentAreaFilled(false);
        BTNRespuesta.setFocusPainted(false);
        BTNRespuesta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNRespuesta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar3.png"))); // NOI18N
        BTNRespuesta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar2.png"))); // NOI18N
        BTNRespuesta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRespuestaActionPerformed(evt);
            }
        });

        LBLPregunta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLPregunta.setForeground(new java.awt.Color(255, 255, 255));
        LBLPregunta.setText("Pregunta:");

        TFRespuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFRespuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFRespuestaKeyTyped(evt);
            }
        });

        LBLContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLContrasena.setForeground(new java.awt.Color(255, 255, 255));
        LBLContrasena.setText("Contrasena:");

        javax.swing.GroupLayout PRespuestaLayout = new javax.swing.GroupLayout(PRespuesta);
        PRespuesta.setLayout(PRespuestaLayout);
        PRespuestaLayout.setHorizontalGroup(
            PRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRespuestaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LBLPregunta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PRespuestaLayout.createSequentialGroup()
                .addGroup(PRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PRespuestaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TFRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PRespuestaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBLContrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(BTNRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        PRespuestaLayout.setVerticalGroup(
            PRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRespuestaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNRespuesta)
                    .addGroup(PRespuestaLayout.createSequentialGroup()
                        .addComponent(LBLPregunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(LBLContrasena)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel22.add(PRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 360, 210));

        LBLCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLCuenta.setForeground(new java.awt.Color(255, 255, 255));
        LBLCuenta.setText("Cuenta:");
        jPanel22.add(LBLCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        TFCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFCuentaKeyTyped(evt);
            }
        });
        jPanel22.add(TFCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setState(General.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BTNCuuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCuuentaActionPerformed
        if (TFCuenta.getText().length() > 0)
        {
            if (vendedor.BuscarUsuario(TFCuenta.getText()))
            {
                TFCuenta.setEnabled(false);
                BTNCuuenta.setEnabled(false);
                PRespuesta.setVisible(true);
                TFRespuesta.setEnabled(true);
                BTNRespuesta.setEnabled(true);
                LBLPregunta.setText(vendedor.ObtenerPregunta(TFCuenta.getText()));
            }
            else
            {
                TFCuenta.setText("");
                JOptionPane.showMessageDialog(null, "El usuario no existe");
            }
                
        }
    }//GEN-LAST:event_BTNCuuentaActionPerformed

    private void BTNRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRespuestaActionPerformed
        if (TFRespuesta.getText().length() > 0)
        {
            if (!vendedor.ObtenerRespuesta(TFCuenta.getText(), TFRespuesta.getText()).equals(""))
            {
                LBLContrasena.setText("Contrasena: " + vendedor.ObtenerContrasena(TFCuenta.getText()));
                BTNRespuesta.setEnabled(false);
                TFRespuesta.setEnabled(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Respuesta incorrecta");
                TFRespuesta.setText("");
            }
                
        }
    }//GEN-LAST:event_BTNRespuestaActionPerformed

    private void TFCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCuentaKeyTyped
        if (TFCuenta.getText().length() > 25) evt.consume();
    }//GEN-LAST:event_TFCuentaKeyTyped

    private void TFRespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFRespuestaKeyTyped
        if (TFRespuesta.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFRespuestaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCuuenta;
    private javax.swing.JButton BTNRespuesta;
    private javax.swing.JLabel LBLContrasena;
    private javax.swing.JLabel LBLCuenta;
    private javax.swing.JLabel LBLPregunta;
    private javax.swing.JPanel PRespuesta;
    private javax.swing.JTextField TFCuenta;
    private javax.swing.JTextField TFRespuesta;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel22;
    // End of variables declaration//GEN-END:variables
}
